# @ehatt
# default window properties and behaviors
# may be significantly different for certain windows, see windowrules.conf

general {
    # controls
    resize_on_border = true
    
    # snapping
    snap {
        enabled = true
        respect_gaps = true
    }
}

decoration {
    dim_inactive = true
}

input {
    # window foucs
    follow_mouse = 1
    float_switch_override_focus = false
}

group {
    # mergig
    drag_into_group = 2
    merge_groups_on_drag = true
    merge_groups_on_groupbar = true
    merge_floated_into_tiled_on_groupbar = true
}

misc {
    # swallowing -- hide terminal when launching apps from it
    enable_swallow = true
   
    # foucs
    mouse_move_focuses_monitor = true
}
