# @ehatt
# general window appearence options
# window appearences for specific apps are handled by windowrules.conf 


source = $colors/cat.conf # Catppuccin colors!
general {
    # borders

    border_size = 4
    col.active_border = $mauve
    col.inactive_border = $lavender

    # gaps
    gaps_in = 5
    gaps_out = 10

    # floating-----

    float_gaps = 5
}

decoration {
    # rounding
    rounding = 15
    rounding_power = 4.0
    
    # default opacity
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    # default dimming
    dim_strength = 0.1
    dim_special = 0.8
    dim_around = 0.3

    # yay blur   
    blur {
        
        # values
        size = 5
        passes = 3
        noise = 0.06
        contrast = 1.5
        brightness = 0.8

        enabled = true
        ignore_opacity = true
        new_optimizations = true
        special = true
        popups = true
        xray = false
    }
    
    # no shadows for now
    shadow {
        enabled = false 
    }
}

# window group styles
group {
    col.border_active = $flamingo
    col.border_inactive = $rosewater

    col.border_locked_active = $red
    col.border_locked_inactive = $maroon

	groupbar {
        font_family = Maple Mono NF propo
        font_size = 20
        text_color = $green
        text_color_inactive = $surface2

        indicator_gap = 8
        indicator_height = 10

		col.active = $rosewater
        col.inactive = $surface2
        col.locked_active = $red
        col.locked_inactive = $maroon

        rounding = 15
        rounding_power = 4.0
  }
}
